{
  "service": "churn-api",
  "provider": {
    "name": "aws",
    "runtime": "nodejs4.3",
    "profile": "churnapi"
  },
  "functions": {
    "api": {
      "handler": "handler.api",
      "events": [
        {
          "http": {
            "path": "graphql",
            "method": "get"
          }
        },
        {
          "http": {
            "path": "graphql",
            "method": "post"
          }
        }
      ]
    }
  }
}